### ISSUE TITLE
Applying on other datasets than flickr30 dataset error

### ISSUE THREAD

**Issue by Souryadipstan** [ExID-proj/VILBERT_tutorial#2]
Traceback (most recent call last):
  File "/Users/sourya/Desktop/vilbert-multi-task/identify_vilbert_emds.py", line 220, in <module>
    main()
  File "/Users/sourya/Desktop/vilbert-multi-task/identify_vilbert_emds.py", line 147, in main
    task_batch_size, task_num_iters, task_id, task_datasets_val, task_dataloader_val = LoadDatasetTransfer(
  File "/Users/sourya/Desktop/vilbert-multi-task/vilbert/task_utils.py", line 408, in LoadDatasetTransfer
    task_datasets_val[task] = DatasetMapTrans[task_name](
  File "/Users/sourya/Desktop/vilbert-multi-task/vilbert/datasets/retreival_dataset.py", line 494, in __init__
    features, num_boxes, boxes, _ = self._image_features_reader[image_id]
  File "/Users/sourya/Desktop/vilbert-multi-task/vilbert/datasets/_image_features_reader.py", line 71, in __getitem__
    index = self._image_ids.index(image_id)
ValueError: b'61' is not in list

This error is showing up when I am trying to generate the Visiolinguistic Embedding. I am using my own dataset. Previously, another bug showed up because, my file names were not integer but strings unlike the flickr30 dataset so, I converted the filenames to integer. After that, this bug is occurring. Any workaround?

**Comment by Souryadipstan** [comment]
Found out the error occurred as I renamed the file after creating the features from the images. File names are also saved as image_id's in the .npy file so, renaming the files first then again generating features fixed the bug.
